
include ../makefile.defs


DIV_DEPS =


all: all_waves all_synth

all_waves: DIV_wave

all_synth: DIV_synth


DIV_wave: VERI_INCL = $(DIV_DEPS)
DIV_wave: DIV.fst


DIV_synth: VERI_INCL = $(DIV_DEPS)
DIV_synth: DIV.blif
